- name: Update apt cache
  apt:
    update_cache: yes

- name: update system
  apt:
    upgrade: dist

- name: set timezone
  timezone:
    name: Europe/Paris

# other good practices
- name: Install essential packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - curl
    - vim
    - htop
    - pip
