FROM golang:1.21

SHELL ["/bin/bash", "-c"]

WORKDIR /app

LABEL org.opencontainers.image.source="https://github.com/Tom-Mendy/Whanos" \
      org.opencontainers.image.title="Whanos golang Base Image" \
      org.opencontainers.image.description="A base image for building and deploying golang applications." \
      org.opencontainers.image.version="1.0"

ONBUILD COPY . /app

ONBUILD RUN set -eux; \
    go build -o compiled-app

ONBUILD CMD ["/app/compiled-app"]
