- name: Install redis
  apt:
    name: redis-server
    state: present

- name: Set up redis
  template:
    src: ../files/redis.conf
    dest: /etc/redis/redis.conf
  register: redis_conf

- name : Restart redis
  systemd:
    name: redis-server
    state: restarted
  when: redis_conf.changed

- name: start redis
  systemd:
    name: redis-server
    state: started
    daemon_reload: true
    enabled: true
