FROM maven:3.9.6 AS build

SHELL ["/bin/bash", "-c"]

WORKDIR /app

LABEL org.opencontainers.image.source=https://github.com/Tom-Mendy/Whanos

ONBUILD COPY pom.xml /app

ONBUILD RUN set -eux; \
            mvn dependency:go-offline

ONBUILD RUN set -eux; \
            rm -rf pom.xml

ONBUILD COPY . /app

ONBUILD RUN set -eux; \
            mvn package


FROM openjdk:21-jdk AS standalone

WORKDIR /app

COPY --from=build /app/target/app.jar app.jar

ONBUILD CMD ["java", "-jar", "app.jar"]
