- name: Upload Registry file
  ansible.builtin.copy:
    src: ../../../../registry
    dest: ~/
    mode: '0644'

- name: Deploy Registry
  community.docker.docker_compose_v2:
    project_src: ~/registry/
    build: always
    pull: always