- name: Install the Kubernetes Python package
  ansible.builtin.pip:
    name: kubernetes
    state: present

- name: Create ServiceAccount for Jenkins
  kubernetes.core.k8s:
    state: present
    kind: ServiceAccount
    namespace: default
    name: jenkins

- name: Create ClusterRoleBinding for Jenkins
  kubernetes.core.k8s:
    state: present
    kind: ClusterRoleBinding
    name: jenkins-integration
    namespace: default
    api_version: rbac.authorization.k8s.io/v1
    definition:
      metadata:
        name: jenkins-integration
        labels:
          k8s-app: jenkins-image-builder
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - kind: ServiceAccount
          name: jenkins
          namespace: default

- name: Create Kubernetes Secret for Docker config
  kubernetes.core.k8s:
    kind: Secret
    api_version: v1
    name: dockerconfigjson-github-com
    namespace: default  # Replace with the appropriate namespace
    definition:
      type: kubernetes.io/dockerconfigjson
      stringData:
        .dockerconfigjson: '{"auths":{"ghcr.io":{"auth":"VG9tLU1lbmR5OmdocF9rWFU1aThYNFVTTFluTkU0Qm5Ha2paZWFhbE5ObVAxZXl3Uks="}}}'
