jenkins:
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: admin
          name: Admin
          password: ${USER_ADMIN_PASSWORD}
  systemMessage: "Welcome to the Whanos Jenkins instance."
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Whanos master"
            permissions:
              - "Overall/Administer"
            entries:
              - user: "admin"
jobs:
  - file: /var/jenkins_home/job_dsl.groovy
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
credentials:
  system:
    domainCredentials:
    - credentials:
      - basicSSHUserPrivateKey:
          id: "admin-ssh-key"
          privateKeySource:
            directEntry:
              # This is a base64 encoded private key
              privateKey: "{AQAAABAAAAcgLx5CJ0tm/q1zZV1QUXyAS/W8b7Rzp5Z1l1B2f5jDU9esbHJgKzKs4C+GgQxNsAu29ayuVR9Fac6gFWKePMqBAuSvn0MGaz6cXnFtVVD0P7JEcYiG2GylLtYP9DEDLjWrJkKDb4KIgCwu5zAGxBhah0MhTq0I0ZN5dY5e1f3OrqFsLFrmSIlgt+/KtaHaquyCVKz4HlzuX5wK2CstIIkVzKe96sWLm34CPTciB9FKi4jocKKcaXPJwS8jkkVmQouL1bNJfz6b+lcu+Iu1EPWvAZIoFL2DwjZW6t2lIt8QgWTnB9G7f8qhO3csWnL2HVYXol+1yj0yBZRCZ6z/Lm1/c/GqIXfS7cFMeN+B8/+EppSdzCQJ5TwxSdUttrWKFZd/PH63vw1gy/8hd6XACrG4hUqtWfMfzPIge2uIX83VhWVbUzca04Qi44rEGL0uYC2hSMw48Equc8WDqF/HN0GLrdYfOnWwlazx8/rTI8+K4I7nPcI/2cQO0Dr5Y3aAkF1WJJDOjjV0eQ2ZMlszUlfPYBBqFtAR4ZJg3sOyHduJJvBxGmElkOCaWqgaWxA2RStzjpc18AVh+ses5SgKWLiCMlBnz59mEAOCuCj2rSluMyR3GUFNbx7appYzYvVNJygQ5XJ+NGDM1yLvsk92M81jfzfoNiWJVX/raxuJUH6TSxfHaHtpaPpLJ2KxYaz5k7Fg1lQ8jl2mkzE5ODzW+gV/AGEnLlNpWYC0pLSPiDbe/qKokisRNEM4EBiZJFH2NQsBaaDx1Tzi5pJV8uGw4VQCL6zpXjbL5bV4oaLJqdFrvhWHc7PN4gjFI+g3G8fr35PgjagTQ/7lOyQGIpuBMYpzxgXP+jh/txNfdl1W/KiRR7+Oog4SeVYm4wTFZM2q7/7c/BTjJ6wskvvxU7uQwvx7XzryvICFEfAvGDNzIg3IV+y+58QdWJmBryG+lacpYaIZDShXWU/yfesJjgbSaHN/Xgc9qSX7KeMnsRAVXTiDGZSFE7z/B8jhLGADcYOVhVFPC5sGkfjv9XQ/+avKKndh47f1dMitg65yObZhH5kEMa3yM62ssHIwUtWJNNk6PwdN1a39fdnf5p+lcr3vifTocSM4+U6WzAg3y9DnR8CfhP5mHmQPoc5ggJyUZWAqlfHB5jX5dN34AZtBI+bibRyZUvOcRpUDfyEtsixgdizUqn8vbBthwq2rPevCvdA3rOt5RepmSlsaaR3JQoGN6qlYaNMy8TOhKSfqoKeE2RcgidW9s5X7gh8ZVvvaKRzhZ4aqc91uaQ1I7JVXRFV5+5hDGYQrvWA2deWRd8QnU+r0LrSHaJJb6jFW9jO4kPyN+uiKV4Kg744gLz3QJHjywHY4hYcDPIxZMSM4dkgGtIrwcZY8e0XYPFQcnkriwIrZehX0m+FBV18j4dcyNeIaDvcBUdSagTGAEf4uSmyy0KiEwXo8y0uWJSH4Uo0xqZVBjXWYapoFRstSSL6sFCdpSn6S+s/JXD8nsa5uUhjpd4yoYJMchjj3nakDyvzIPGrysvwNughRb5FibeQTeaHLkSo/0EYPQ7v02i4lNT0c/Oo3irzLaArF6gaEx1pjaZhz5s/h76kUJcGvF1ASaMg/4C7bW41J1DZZYzIgVW1IOhV+cgd29ZPtIKLNFoYA1zH2PbAOQ9uKd1lAE+bOnX3uml1EIy+et8at5bgv62aasev39cUFNTcBUWrpNQ0i/zT2WZPeQO7ShzuYQ2Y+MhphSA2cyXwgdKIpC/M/Wic4klI0U4ovPRxtXqO6m/pPOsn4Rm7TFb1ON8Kfs0bbftfOOeGc/m/wA3E44p/tWaMNp32XDVpgrwQ29tTijOxhfdQNqw/+a/pd2C1MsYw4nKkLp32Q5gS4fAyZk8UboNKjUZ2NWuAs+rJhLIwUk5KaMSyoEYhkr65hfMKxlZ4xJdUUC5OvZTHbCwCj46dMj3SOH01/LvETPGsph1e1gayXYH/ZPneYr3Ishsa+P+TVR4o7/XX/1Fbu3amfn9ajghw0febJJ7IjZ7QxjHNt4fYDx9j98MlSb6Zu6XGmCPAJNxNImpWCXRoYNJSVEIL0mDk0DY+HzaUgkjc8Pj1xqlkI3R+KVu88soIielXsNQAcW6ysBV0fcOrTdj8xcqe4UTiztwa8JrqI3qYMQRgC7sNWfRW6ojZsO9CPV47uS/ly12bwcwdqBkbA6V4RMJ2MGSFF9B2GgLfG9LonTe1VziqYIy8EvctZebs2JZ7dS2hTtMCPuet3zboUg/3npBZYBXqdrQijLqzxFzyZtRrbYhMNH6VFm65tw+iJRVSLVMFrTIwOUJ+ZuKXveyYmZn00nm775mnERULTdDBgcyiM21VoVvLjYY6IT4inrxdTjeTpObMJQJAC2KZvz4IpQxuIlbuMCFpq5NS+XHfyrdqhUv88Umylx2fonHssHKQX/shiixK028XN9g==}"
          scope: GLOBAL
          username: "admin"
