jenkins:
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: admin
          name: Admin
          password: ${USER_ADMIN_PASSWORD}
  systemMessage: "Welcome to the Whanos Jenkins instance."
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Whanos master"
            permissions:
              - "Overall/Administer"
            entries:
              - user: "admin"
jobs:
  - file: /var/jenkins_home/job_dsl.groovy
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "AcceptFirstConnectionStrategy"
credentials:
  system:
    domainCredentials:
    - credentials:
      - basicSSHUserPrivateKey:
          id: "admin-ssh-key"
          privateKeySource:
            directEntry:
              # This is a base64 encoded private key
              privateKey: ${SSH_PRIVATE_KEY}
          scope: GLOBAL
          username: "admin"
