jenkins:
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: admin
          name: Admin
          password: ${USER_ADMIN_PASSWORD}
  systemMessage: "Welcome to the Whanos Jenkins instance."
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Whanos master"
            permissions:
              - "Overall/Administer"
            entries:
              - user: "admin"
jobs:
  - file: /var/jenkins_home/job_dsl.groovy
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
credentials:
  system:
    domainCredentials:
    - credentials:
      - basicSSHUserPrivateKey:
          id: "admin-ssh-key"
          privateKeySource:
            directEntry:
              # This is a base64 encoded private key
              privateKey: "LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJGd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFRRUFzTUhSVmkvZzFGcmVMdVN0eks5bEZOREJ2VTFjMXFQSGdrUWM2MlBXUUhvWUpaUEU2bWo3CkJrVFhHbFhhbWMzYVFUZkhBVG9QME9BUHpHZUVGSFlhNFlBS2xDU3NOc0NDWHZ6UEhiaGVmVEE0NCttakJ3QUtZOGVpS3EKRnp1Qzh5NU9PQ0tyclFEK3cxWDBLdTdjZ0VoMUdqQ0tSM3dTSENsQUQ0YUhKSEpGazNQVUpHckhWM0oxZE9NVTI4QUgwVApIRXd0U0d6SmhXY2c1MlFnOUhTeW9XQndVRWlQci91SU1wdDZlekljclZOcGM3bTdDTW4zMUs0cjhYdmhlM1dJaVBlUTFLClNuZXVyTHB0c09wSFpISHJlRi8xa1ErT1dDd1ROL0VQZ1pCdHZmOTI1NmU0bHYxb0NoVTRDNUV0dTEyTHNkYjJjSkJtbjIKTUJndE1lRWs4d0FBQThpS1ZDM09pbFF0emdBQUFBZHpjMmd0Y25OaEFBQUJBUUN3d2RGV0wrRFVXdDR1NUszTXIyVVUwTQpHOVRWeldvOGVDUkJ6clk5WkFlaGdsazhUcWFQc0dSTmNhVmRxWnpkcEJOOGNCT2cvUTRBL01aNFFVZGhyaGdBcVVKS3cyCndJSmUvTThkdUY1OU1Eamo2YU1IQUFwang2SXFvWE80THpMazQ0SXF1dEFQN0RWZlFxN3R5QVNIVWFNSXBIZkJJY0tVQVAKaG9ja2NrV1RjOVFrYXNkWGNuVjA0eFRid0FmUk1jVEMxSWJNbUZaeURuWkNEMGRMS2hZSEJRU0krdis0Z3ltM3A3TWh5dApVMmx6dWJzSXlmZlVyaXZ4ZStGN2RZaUk5NURVcEtkNjZzdW0ydzZrZGtjZXQ0WC9XUkQ0NVlMQk0zOFErQmtHMjkvM2JuCnA3aVcvV2dLRlRnTGtTMjdYWXV4MXZad2tHYWZZd0dDMHg0U1R6QUFBQUF3RUFBUUFBQVFCRCtFd1pBZkZKaDZYUHo0VWIKNUVpUkFCTzRTVk1OZ001OEE5aEJGbE94MktHSGRiTHYxeTNNZzlWWm5iRWhtdHkyWG80S3BUcW12anFsQmh0dXlObmVaQgovdFJzcm9oUSs5R2lkRkRQeGMxSm5UM3FpZnpQNnh6dmRId0cwZzR4bUZsZzBjaEZqMC9vYXBtcGxzKzVEdVBsRGN4bTM4Cm1SQmJYS0lwZStScWo3Wm5uNU1od1k3ZlU5UDhHdXRJMW1QWVBDRldFR3JnUUNMWTBEZVVXRHV0NFdxeVRITENkUXJBei8KNWNTdVZJZlVpUHpJRkg0N2JibU5mVHRPYlMxSVFGTGhXL2ZNSW4wVWhSZ1JBakpvQ0RLTVJaUVpqRE9kNEFtYjZLZEhDZAppNkxKdXY4bG5rUEtSMlhldXZLY0VnazZLZzl2ckhzeVptMld0VWlObm1abEFBQUFnUUNBb1JxVFZ3dXpmYUNCU2VkczczCjJlRnBDK2JSdnlPbFRrd05HQ2kxVjhVcmJjVitSb0FWZDhXbFl2WnhkYitnaThyY1RkSlhZYm5qN2RadzcwRTBXRllkVG0KR2d5d01rNEkweXdtalE1dVovd0xQU3Y5Q29HNTFwUEVPT1ordFFKM2o5eU4rNGhaaDgzdGc3aHA2ZzlGU29aYnVCNTR0TgphTHhZbnFBc2ZmMndBQUFJRUEzWU1kWnJxNEJGeFFFenJiY3Q4M1JNVFUvc09SUThoQnhSKzF1NTZkdDdsdWlVaUwwYVAxCjRZbERycjgvRUpGc1g0WktUQ256RXZYWnZQUU1Xa0RueUNubWlFS1VGNDlzNU8vdEJmaUlET2RmOTF2NkFFZjVVNmtKQS8KYWxyMnhJUGdQNTd0QW5wTUcyUDJ1RHRyRDdaSEhJWDkrYlJYWkVkZDFYZVFNTXZhVUFBQUNCQU14RzRwU01IY0JQbHZtTApoeTZhd0g1M2tNT2tzMTR5VnhENTRJQjdkbGg1K05yYnpVb1Q0dkJHR2NOejBGOHNVOWVKaWlOVFY5QTRpMW9JaEE2NGRJClVxOVpqY1pZOFEycURZRlFKWWs2QWNWc0V0Ly9XbG11bGI5Q1RFVXN3OVJ0Nk9SR3cyc2s2NW1XSWFYVU9sNmZSNzFlRlcKRkF6cWhhWGxreE55WXdTM0FBQUFFWFJ0Wlc1a2VVQlViMjB0Um1Wa2IzSmhBUT09Ci0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQo="
          scope: GLOBAL
          username: "admin"
