services:
  jenkins:
    container_name: jenkins
    pull_policy: always
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ../images:/var/jenkins_home/docker_images
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - USER_ADMIN_PASSWORD=${USER_ADMIN_PASSWORD:-password}
      # https://github.com/OWNER/REPO GITHUB_DOCKER_REGISTRY=OWNER/REPO
      - GITHUB_DOCKER_REGISTRY_REPO=${GITHUB_DOCKER_REGISTRY_REPO:-OWNER/Whanos}
      # GITHUB_DOCKER_REGISTRY must be lowercase GITHUB_DOCKER_REGISTRY=owner
      - GITHUB_DOCKER_REGISTRY=${GITHUB_DOCKER_REGISTRY:-owner}
      - GITHUB_DOCKER_REGISTRY_USERNAME=${GITHUB_DOCKER_REGISTRY_USERNAME:-username}
      - GITHUB_DOCKER_REGISTRY_TOKEN=${GITHUB_DOCKER_REGISTRY_TOKEN:-github_token}
      # SSH_PRIVATE_KEY
      - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY:-private_key}
      - SSH_PASSPHRASE=${SSH_PASSPHRASE} # Optional
    user: root

volumes:
  jenkins_home:
