services:
  jenkins:
    container_name: jenkins
    pull_policy: always
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ../images:/var/jenkins_home/docker_images
      - ../kubernetes:/var/jenkins_home/kubernetes
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - USER_ADMIN_PASSWORD=${USER_ADMIN_PASSWORD:-password}
      # GITHUB_DOCKER_REGISTRY must be lowercase GITHUB_DOCKER_REGISTRY=owner
      - GITHUB_DOCKER_REGISTRY=${GITHUB_DOCKER_REGISTRY:-owner}
      - GITHUB_DOCKER_REGISTRY_USERNAME=${GITHUB_DOCKER_REGISTRY_USERNAME:-username}
      - GITHUB_DOCKER_REGISTRY_TOKEN=${GITHUB_DOCKER_REGISTRY_TOKEN:-github_token}
      # SSH_PRIVATE_KEY
      - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY:-private_key}
      # kubernetes
      - KUBE_SERVER=${KUBE_SERVER}
      - KUBE_TOKEN=${KUBE_TOKEN}
    user: root

volumes:
  jenkins_home:
