services:
  jenkins:
    container_name: jenkins
    pull_policy: always
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ../images:/var/jenkins_home/docker_images
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - USER_ADMIN_PASSWORD=${USER_ADMIN_PASSWORD:-password}
    user: root
    env_file:
      - .env

volumes:
  jenkins_home:
