services:
  jenkins:
    container_name: jenkins
    pull_policy: always
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - USER_ADMIN_PASSWORD=${USER_ADMIN_PASSWORD:-password}

volumes:
  jenkins_home:
