- hosts: jenkins
  become: true
  roles:
    - base
    - docker
    - jenkins

# - hosts: postgresql
#   become: true
#   roles:
#     - postgresql

# - hosts: poll
#   become: true
#   roles:
#     - poll

# - hosts: worker
#   become: true
#   roles:
#     - worker

# - hosts: result
#   become: true
#   roles:
#     - result