- hosts: terraform
  become: true
  roles:
    - terraform

- hosts: jenkins
  become: true
  roles:
    - base
    - docker
    - jenkins

- hosts: registry
  become: true
  roles:
    - base
    - docker
    - registry
