# - hosts: localhost
#   become: false
#   roles:
#     - terraform

- hosts: jenkins
  become: true
  roles:
    - base
    - docker
    - jenkins

- name: Install Kubernetes
  ansible.builtin.import_playbook: kubernetes_sigs.kubespray.cluster