- hosts: jenkins
  become: true
  roles:
    - base
    - docker
    - jenkins
  vars:
    REGISTRY_HOST: "{{ hostvars[groups['registry'][0]].get('ansible_host', inventory_hostname) }}"

- hosts: registry
  become: true
  roles:
    - base
    - docker
    - registry

# - hosts: poll
#   become: true
#   roles:
#     - poll

# - hosts: worker
#   become: true
#   roles:
#     - worker

# - hosts: result
#   become: true
#   roles:
#     - result