- hosts: jenkins
  become: true
  roles:
    - base
    - docker
    - jenkins

- hosts: registry
  become: true
  roles:
    - base
    - docker
    - registry

# - hosts: poll
#   become: true
#   roles:
#     - poll

# - hosts: worker
#   become: true
#   roles:
#     - worker

# - hosts: result
#   become: true
#   roles:
#     - result