- hosts: localhost
  become: false
  roles:
    - terraform

- hosts: kube_control_plane
  roles:
    - base
    - docker

- hosts: kube_node
  roles:
    - base
    - docker

- name: Install Kubernetes
  ansible.builtin.import_playbook: kubernetes_sigs.kubespray.cluster

- hosts: kube_control_plane
  roles:
    - kubernetes

- hosts: jenkins
  become: true
  roles:
    - base
    - docker
    - jenkins