FROM gcc:13.2 AS build

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y --no-install-recommends \
    cmake \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . /app

RUN set -eux; \
    cmake -S . -B build

RUN set -eux; \
    cmake --build build


FROM ubuntu:24.04 AS standalone

SHELL ["/bin/bash", "-c"]

WORKDIR /app

COPY --from=build /app/compiled-app /app/compiled-app

CMD ["/app/compiled-app"]
