FROM python:3.12

SHELL ["/bin/bash", "-c"]

WORKDIR /app

LABEL org.opencontainers.image.source=https://github.com/Tom-Mendy/Whanos

ONBUILD COPY requirements.txt /app

ONBUILD RUN set -eux; \
            pip install -r requirements.txt

ONBUILD RUN set -eux; \
            rm -rf requirements.txt

ONBUILD COPY . /app

ONBUILD CMD ["python", "-m", "app"]