FROM python:3.12 AS dependencies

SHELL ["/bin/bash", "-c"]

WORKDIR /app

COPY requirements.txt /app

RUN pip install -r requirements.txt

FROM dependencies AS standalone

SHELL ["/bin/bash", "-c"]

WORKDIR /app

COPY . /app

COPY --from=dependencies /app/app /app

CMD ["python", "-m", "app"]
