FROM debian:stable-slim

RUN set -eux; \
    apt-get update && apt-get install -y --no-install-recommends \
        nodejs \
        npm

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

LABEL org.opencontainers.image.source=https://github.com/Tom-Mendy/Whanos

CMD ["node", "."]
