FROM node:20.9

SHELL ["/bin/bash", "-c"]

WORKDIR /app

LABEL org.opencontainers.image.source=https://github.com/Tom-Mendy/Whanos

ONBUILD COPY . /app

ONBUILD RUN set -eux; \
            npm install

ONBUILD CMD ["node", "."]
