FROM node:20.9 AS dependencies

SHELL ["/bin/bash", "-c"]

WORKDIR /app

COPY package.json /app

RUN npm install

COPY . /app

FROM dependencies AS standalone

SHELL ["/bin/bash", "-c"]

WORKDIR /app

COPY --from=dependencies /app/app /app

CMD ["node", "."]