FROM node:20.9

SHELL ["/bin/bash", "-c"]

WORKDIR /app

LABEL org.opencontainers.image.source="https://github.com/Tom-Mendy/Whanos" \
      org.opencontainers.image.title="Whanos javascript Base Image" \
      org.opencontainers.image.description="A base image for building and deploying javascript applications using node." \
      org.opencontainers.image.version="1.0"

ONBUILD COPY . /app

ONBUILD RUN set -eux; \
            npm install

ONBUILD CMD ["node", "."]
